# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ConnHex
email: and.xet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ConnHex the game that won the Turin Global Game Jam 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://connhex.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "loalhost:4000"
#twitter-username: connhex
#facebook-username: connhex
#github_username:  connhex

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate 
#  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /projects/:path/

team:
  - name: Andrea Crivello
    role: 2D/3D Artist
    picture: /img/team/crivello.png
    socials:
      website: http://www.andreacrivello.com
      twitter: https://twitter.com/CrivelloAndrea
      linkedin: https://www.linkedin.com/in/andrea-crivello-33446874/
      instagram: https://www.instagram.com/crivelloandrea_3d/
  - name: Lorenzo Valente
    role: Developer
    picture: /img/team/valente.png
    socials:
      website: https://about.me/lorenzovalente
      twitter: https://twitter.com/Oneiros90
      linkedin: https://www.linkedin.com/in/valentelorenzo/
  - name: Dario Facchini
    role: Developer
    picture: /img/team/facchini.png
    socials:
      linkedin: https://www.linkedin.com/in/dariofacchini/
      github: https://github.com/fakkoweb
  - name: Andrea Peretti
    role: Developer
    picture: /img/team/peretti.png
    socials:
      website: http://www.andxet.com
      github: https://github.com/andxet
      bitbucket: https://bitbucket.com/andxet
      # twitter: https://twitter.com/andxet
      linkedin: https://www.linkedin.com/in/andreaperetti/

socials:
  twitter: https://twitter.com/ConnHex
  instagram: https://www.instagram.com/connhex/
  facebook: https://www.facebook.com/ConnHex/

instructions:
  - image: /img/instructions/instruction_001.png
    title: Use your smartphone as gamepad!
    description: Click on "Play Now!" to to start the game! From your smartphone go to www.airconsole.com and insert the code shown in your PC.
  - image: /img/instructions/instruction_002.png
    title: Move around
    description: Your spaceship will automatically move, use the buttons on your touchscreen to turn. Press both them to shoot and stop.
  - image: /img/instructions/instruction_003.png
    title: Conquer your field!
    description: Go over a cell to conquer it!<br/>You can conquer a cell only if it is linked with your nucleus
  - image: /img/instructions/instruction_004.png
    title: Destroy the enemy's nucleus!
    description: Create a link with the enemy's nucleus to make it vulnerable! The vulnerable cores are damaged constatly when time passes. Shoot it to reduce its energy faster!
  - image: /img/instructions/instruction_005.png
    title: Defend your nucleus!
    description: Conquer cells to cut the opponent's path, press both the buttons shoot them and kill them.

play-now-address: https://www.airconsole.com/#https://storage.googleapis.com/com.illogeek.connhex.cdn.airconsole.com/2018-03-09-00-00-25/

paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: 
    - reference
    - Gemfile
    - Gemfile.lock
    - LICENSE.txt
    - README.txt
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
