# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ConnHex
email: and.xet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ConnHex the game that won the Turin Global Game Jam 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://connhex.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "loalhost:4000"
#twitter-username: connhex
#facebook-username: connhex
#github_username:  connhex

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate 
#  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /projects/:path/

team:
  - name: Andrea Crivello
    role: 2D/3D Artist
    picture: /img/crivello.png
    website: http://www.andreacrivello.com
    twitter: https://twitter.com/CrivelloAndrea
    Linkedin: https://www.linkedin.com/in/andrea-crivello-33446874/
    Instagram: https://www.instagram.com/crivelloandrea_3d/
  - name: Lorenzo Valente
    role: Developer
    picture: /img/valente.png
    website: https://about.me/lorenzovalente
  - name: Dario Facchini
    role: Developer
    picture: /img/facchini.png
  - name: Andrea Peretti
    picture: /img/peretti.png
    role: Developer
    website: http://www.andxet.com
    github: https://github.com/andxet
    bitbucket: https://bitbucket.com/andxet
#    twitter: https://twitter.com/andxet
    linkedin: https://www.linkedin.com/in/andreaperetti/


paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: 
    - reference
    - Gemfile
    - Gemfile.lock
    - LICENSE.txt
    - README.txt
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
